### ISSUE TITLE
PyDownTV2 Script: Falla descarga por consola

### ISSUE THREAD

**Issue by DJJuls** [aabilio/PyDownTV2#100]
Tengo instalado PyDownTV2 Script, en una raspberry y hasta hace poco funcionaba bien. He descargado la última versión pero sigue fallando. Este es el error:

pi@raspbmc:~$ pydowntv.py http://www.mitele.es/programas-tv/cuarto-milenio/temporada-9/programa-351/

[ URL ] http://www.mitele.es/programas-tv/cuarto-milenio/temporada-9/programa-351/ 
[INFO] Mitele.es 
[INFO] ID: /nogeo/programa/cuartomilenio/t9/c351_904e76a0.mp4 
Traceback (most recent call last):
  File "/usr/local/bin/pydowntv.py", line 5, in <module>
    pkg_resources.run_script('PydownTV==0.1.0', 'pydowntv.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/PydownTV-0.1.0-py2.7.egg/EGG-INFO/scripts/pydowntv.py", line 205, in <module>
    info = canal.getInfo()
  File "/usr/local/lib/python2.7/dist-packages/PydownTV-0.1.0-py2.7.egg/spaintvs/mitele.py", line 223, in getInfo
    url = self.**getUrl2down(ID, startTime, endTime, htmlBackup)
  File "/usr/local/lib/python2.7/dist-packages/PydownTV-0.1.0-py2.7.egg/spaintvs/mitele.py", line 63, in __getUrl2down
    server_time = Descargar.get(self.URL_TIME).strip()
  File "/usr/local/lib/python2.7/dist-packages/PydownTV-0.1.0-py2.7.egg/spaintvs/Descargar.py", line 158, in getHtml
    else: return getHtml_(url).decode('string-escape')
  File "/usr/local/lib/python2.7/dist-packages/PydownTV-0.1.0-py2.7.egg/spaintvs/Descargar.py", line 130, in getHtml_
    raise ErrorDescarga(e.__str**())
spaintvs.Descargar.ErrorDescarga: HTTP Error 404: Not Found
pi@raspbmc:~$

**Comment by aabilio** [comment]
La actualizo esta noche

**Comment by aabilio** [comment]
Descarga la última versión del script. Ahora debería funcionar. Saludos.

**Comment by aabilio** [comment]
```
    Weknow - Invitación

    *{margin:0;padding:0;font-family:"Helvetica Neue","Helvetica",Helvetica,Arial,sans-serif}img{max-width:100%}.collapse{margin:0;padding:0}body{-webkit-font-smoothing:antialiased;-webkit-text-size-adjust:none;width:100%!important;height:100%}a{color:#34AD9B}.btn{text-decoration:none;padding:10px 16px;font-weight:700;margin-right:10px;text-align:center;cursor:pointer;display:inline-block}.btn.one{color:#fff;background-color:#4C237E}.btn.two{color:#fff;background-color:#34AD9B}.btn.three{color:#fff;background-color:#c931c9}p.callout{padding:15px;background-color:#34AD9B;margin-bottom:15px}.callout a{font-weight:700;color:#2BA6CB}table.social{background-color:#ebebeb}.social .soc-btn{padding:3px 7px;font-size:12px;margin-bottom:10px;text-decoration:none;color:#FFF;font-weight:700;display:block;text-align:center}a.fb{background-color:#3B5998!important}a.tw{background-color:#1daced!important}a.gp{background-color:#DB4A39!important}a.ms{background-color:#000!important}.sidebar .soc-btn{display:block;width:100%}table.head-wrap{width:100%}.header.container table td.logo{padding:15px}.header.container table td.label{padding:15px;padding-left:0}table.body-wrap{width:100%}table.footer-wrap{width:100%;clear:both!important}.footer-wrap .container td.content p{border-top:1px solid #d7d7d7;padding-top:15px;font-size:10px;font-weight:700}h1,h2,h3,h4,h5,h6{font-family:"HelveticaNeue-Light","Helvetica Neue Light","Helvetica Neue",Helvetica,Arial,"Lucida Grande",sans-serif;line-height:1.1;margin-bottom:15px;color:#000}h1 small,h2 small,h3 small,h4 small,h5 small,h6 small{font-size:60%;color:#6f6f6f;line-height:0;text-transform:none}h1{font-weight:200;font-size:44px}h2{font-weight:200;font-size:37px}h3{font-weight:500;font-size:27px}h4{font-weight:500;font-size:23px}h5{font-weight:900;font-size:17px}h6{font-weight:900;font-size:14px;text-transform:uppercase;color:#444}.collapse{margin:0!important}p,ul{margin-bottom:10px;font-weight:400;font-size:14px;line-height:1.6}p.lead{font-size:17px}p.last{margin-bottom:0}ul li{margin-left:5px;list-style-position:inside}ul.sidebar{background:#ebebeb;display:block;list-style-type:none}ul.sidebar li{display:block;margin:0}ul.sidebar li a{text-decoration:none;color:#666;padding:10px 16px;cursor:pointer;border-bottom:1px solid #777;border-top:1px solid #FFF;display:block;margin:0}ul.sidebar li a.last{border-bottom-width:0}ul.sidebar li a h1,ul.sidebar li a h2,ul.sidebar li a h3,ul.sidebar li a h4,ul.sidebar li a h5,ul.sidebar li a h6,ul.sidebar li a p{margin-bottom:0!important}.container{display:block!important;max-width:600px!important;margin:0 auto!important;clear:both!important}.content{padding:15px;max-width:600px;margin:0 auto;display:block}.content table{width:100%}.column{width:300px;float:left}.column tr td{padding:15px}.column-wrap{padding:0!important;margin:0 auto;max-width:600px!important}.column table{width:100%}.social .column{width:280px;min-width:279px;float:left}.clear{display:block;clear:both}@media only screen and (max-width: 600px){a[class="btn"]{display:block!important;margin-bottom:10px!important;background-image:none!important;margin-right:0!important}div[class="column"]{width:auto!important;float:none!important}table.social div[class="column"]{width:auto!important}}












                            Ayudando al mundo a elegir mejor


















                            Hola, reply@reply.github.com
                            Tu amig@ Abilio 👾 Almeida Eiroa (@aabilio) te ha invitado a unirte a Weknow
                            Weknow es una red social donde podrás crear preguntas visuales y tomar decisiones en base a las votaciones de tus amigos.


                                Join us
                                Android
                                iOS




















                                © Weknow Creative SL 2014 | Made with ♥ in Vigo
```
