### ISSUE TITLE
TVE no funciona

### ISSUE THREAD

**Issue by rosiewin** [aabilio/PyDownTV2#144]
No hay forma de descargar capitulos de RTVE A la carta. Todos dan o error 404 o archivo htm

**Comment by aabilio** [comment]
¿Podrías ponerme alguna url de ejemplo?

Saludos.

**Comment by rosiewin** [comment]
He probado varias, pero por poner ejemplo:

Htm: http://www.rtve.es/alacarta/videos/cuentame-como-paso/cuentame-como-paso-t7-capitulo-111/880592/

Error 404: http://www.rtve.es/alacarta/videos/amar-en-tiempos-revueltos/amar-tiempos-revueltos-t2-capitulo-132/425711/

**Comment by aabilio** [comment]
El primer ejemplo a mí me funciona: http://www.pydowntv.com/?url=http%3A//www.rtve.es/alacarta/videos/cuentame-como-paso/cuentame-como-paso-t7-capitulo-111/880592/

El segundo es verdad que no, tengo que echarle un vistazo ;)

**Comment by rosiewin** [comment]
El primer ejemplo y todos los demas videos que he probado (capitulos de la misma serie y de amar en tiempos revueltos) me dan un archivo htm 

Probé ayer y probé hoy... y ya no sé qué más probar XD porque me da lo mismo tanto si uso la extensión como si copipasteo el enlace. Incluso el que has puesto tú me da un archivo htm.

**Comment by aabil** [comment]
Esto me sale a mi al intentar descargar dibujos del clan con el script:

pydowntv.py http://www.rtve.es/infantil/videos-juegos/#/videos/baby-looney-tunes/todos/petunia-hucha/2681823/
Traceback (most recent call last):
  File "/usr/local/bin/pydowntv.py", line 5, in <module>
    pkg_resources.run_script('PydownTV==0.1.0', 'pydowntv.py')
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 489, in run_script
    set's `.entries` (if it wasn't already present).
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 1207, in run_script
    exec script_code in namespace, namespace
  File "/usr/local/lib/python2.7/dist-packages/PydownTV-0.1.0-py2.7.egg/EGG-INFO/scripts/pydowntv.py", line 29, in <module>
    from spaintvs import *
  File "/usr/local/lib/python2.7/dist-packages/PydownTV-0.1.0-py2.7.egg/spaintvs/grupo_a3.py", line 36, in <module>
    from secrets import A3PLAYER_SECRET
ImportError: No module named secrets

**Comment by aabilio** [comment]
@aabil necesitas un fichero en "/usr/local/lib/python2.7/dist-packages/PydownTV-0.1.0-py2.7.egg/spaintvs/" que se llame "secrets.py" y que tenga este contenido:

```
A3PLAYER_SECRET = ''
```

Eso o volver a hacer el clone (o checkout de tu repo) en donde haya el archivo "configure.py" en la raiz del proyecto y pasarlo..

Ejemplo:

```
git clone https://github.com/aabilio/PyDownTV2.git
cd PyDownTV2/
git reset --hard d75b7cbfdae1a0947c50614e3fe1c7d71ae7d8ec
python ./configure.py 
cd Script/
sudo python setup.py install
```

**Comment by aabilio** [comment]
@rosiewin aun no he tenido tiempo de ver qué está pasando.. sorry

**Comment by aabil** [comment]
@aabilio, lo he vuelto a instalar como indicas (había olvidado el configure...), pero sigue sin funcionar:

pydowntv.py http://www.rtve.es/infantil/videos-juegos/#/videos/baby-looney-tunes/todos/petunia-hucha/2681823/

[ URL ] http://www.rtve.es/infantil/videos-juegos/#/videos/baby-looney-tunes/todos/petunia-hucha/2681823/ 
[INFO] Radio Televión Española 
[INFO] ID del Vídeo : 2681823 
[INFO] Vídeo de Clan 
Traceback (most recent call last):
  File "/usr/local/bin/pydowntv.py", line 5, in <module>
    pkg_resources.run_script('PydownTV==0.1.0', 'pydowntv.py')
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 489, in run_script
    set's `.entries` (if it wasn't already present).
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 1207, in run_script
    exec script_code in namespace, namespace
  File "/usr/local/lib/python2.7/dist-packages/PydownTV-0.1.0-py2.7.egg/EGG-INFO/scripts/pydowntv.py", line 209, in <module>
    info = canal.getInfo()
  File "/usr/local/lib/python2.7/dist-packages/PydownTV-0.1.0-py2.7.egg/spaintvs/tve.py", line 211, in getInfo
    return self.__ClanTV(sourceHTML, videoID)
  File "/usr/local/lib/python2.7/dist-packages/PydownTV-0.1.0-py2.7.egg/spaintvs/tve.py", line 104, in __ClanTV
    url = self.URL_RTVE+Utiles.recortar(data, "url=\"", "\"")
  File "/usr/local/lib/python2.7/dist-packages/PydownTV-0.1.0-py2.7.egg/spaintvs/Utiles.py", line 68, in recortar
    return orig.split(str1)[1].split(str2)[0]
IndexError: list index out of range

**Comment by aabilio** [comment]
@aabil eso es que va bien, pero ahora mismo están fallando algunos vídeos de RTVE (como comenta @rosiewin más arriba), en cuanto pueda, le echo un ojo ;)
