### ISSUE TITLE
Error en el Script (¿o me falta algo en mi Python?)

### ISSUE THREAD

**Issue by jotego** [aabilio/PyDownTV2#145]
Hola, estoy probando la versión de Script en Ubuntu 14.04 y después de ejecutar 
sudo python setup.py install

Aun me da el siguiente error al tratar de descargar contenido: 

Traceback (most recent call last):
  File "./pydowntv.py", line 209, in <module>
    info = canal.getInfo()
  File "/home/xxx/src/PyDownTV2/Script/spaintvs/grupo_a3.py", line 710, in getInfo
    return self.atresplayer_mobile()
  File "/home/xxx/src/PyDownTV2/Script/spaintvs/grupo_a3.py", line 505, in atresplayer_mobile
    raise Error.GeneralPyspainTVsError(unicode(jj['resultDes']))
NameError: global name 'jj' is not defined

¿Qué podría ser? El "commit" que estoy viendo es cbd15d24d3631a4fee23fd64fd89f53759f2f319

Gracias.

**Comment by aabilio** [comment]
```
git clone https://github.com/aabilio/PyDownTV2.git
cd PyDownTV2/
git reset --hard d75b7cbfdae1a0947c50614e3fe1c7d71ae7d8ec
python ./configure.py 
cd Script/
sudo python setup.py install
```

**Comment by jotego** [comment]
Gracias pero sigo con el mismo error. Después de haber ejecutado todos los
comandos recomendados:

Script $ python pydowntv.py
http://www.atresplayer.com/television/programas/mas-vale-tarde/2014/julio/dia-25-brcenas-vuelve-pedir-ruz-que-desbloqueen-cuentas-bancarias-pagar-hacienda_2014072500328.html

[ URL ]
http://www.atresplayer.com/television/programas/mas-vale-tarde/2014/julio/dia-25-brcenas-vuelve-pedir-ruz-que-desbloqueen-cuentas-bancarias-pagar-hacienda_2014072500328.html
[INFO] Grupo Antena 3 (- La Sexta)
Traceback (most recent call last):
  File "pydowntv.py", line 209, in <module>
    info = canal.getInfo()
  File "/home/jtejada/PyDownTV2/Script/spaintvs/grupo_a3.py", line 710, in
getInfo
    return self.atresplayer_mobile()
  File "/home/jtejada/PyDownTV2/Script/spaintvs/grupo_a3.py", line 505, in
atresplayer_mobile
    raise Error.GeneralPyspainTVsError(unicode(jj['resultDes']))
_NameError: global name 'jj' is not defined_

Ese jj del error se me escapa. ¿Qué es? ¿Falta alguna libreria?

2014-07-28 12:46 GMT+02:00 Abilio Almeida (aabilio) <
notifications@github.com>:
