### ISSUE TITLE
No deja descargar desde mtv.es

### ISSUE THREAD

**Issue by melguel** [aabilio/PyDownTV2#35]
Intentando descargar el episodio de Alaska y Mario 3x01, la consola del sistema da el error NetStream.Play.SreamNot Found, no se si es porque hago algo mal o es mtv que no lo bloquea, muchas gracias. 
![captura](https://f.cloud.github.com/assets/4508409/553846/9035447e-c393-11e2-9a22-12ebd51526f6.jpg)

**Comment by aabilio** [comment]
Me puedes pegar aquí el enlace de MTV para cuando pueda hacer pruebas, por favor?

**Comment by melguel** [comment]
¡qué veloz! mira el enlace de mtv es este
http://www.mtv.es/programas/destacados/alaska-mario-tercera-temporada/videos/alaska-y-mario-ep-301-parte-1-de-2-909342/
y el que te proporciona es este
rtmpdump -r 'rtmpe://cp35019.edgefcs.net/ondemand/mtviestor/_!/intlod/es/tv/ALASKA_Y_MARIO_3TEMP/aym-301_768x432_1700_m30.mp4' -o 'Alaska_y_Mario_Ep.301_Parte_1_de_2.mp4'
muchas gracias!

**Comment by aabilio** [comment]
No lo he dejado descargar hasta el final, estoy trabajando y no le puedo prestar mucha atención ahora.. pero sí me ha empezado a descargar con el comando de rtmpdump que me proporcionas.
Puede que sea problemas con las comillas, prueba a editar el comando una vez pegado y donde aparecen esas pseudo comillas cambiarlas por unas comillas simples (las de la misma tecla que el cierre de interrogación) que introduzcas tú a través del teclado de tu PC. Si usas Windows, puede que necesites incluso comillas dobles (las de la misma tecla que el número 2), prueba a cambiarlas entonces a mano una vez pegado el comando en la consola.
Haz estas pruebas y comenta si te ha resultado...
Sino, puede que sea por una versión diferente de RTMPDUMP, prueba a buscar por internet si encuentras alguna más actualizada..
De momento no se me ocurre nada más.
Saludos.

**Comment by melguel** [comment]
He intentado hacerlo en otro ordenador (ambos con Windows 7) con la version de RTMPDUMP 2.4, que creo que es la ultima, y nada... Cambiando las comillas me sale otro mensaje 
![sin ttulo](https://f.cloud.github.com/assets/4508409/560337/273c55ae-c472-11e2-8158-1af916697d6a.png)
No se me ocurre que haré, voy a ver si con otra versión anterior quizá, ¡gracias!

**Comment by melguel** [comment]
Solucionado! He instalado otra vez, y eso sí cambiando a comillas normales, y escribiendo a mano rmtpdump.exe, esta vez sí me permitió descargar, ¡muchas gracias!

**Comment by aabilio** [comment]
Puedes dejar escrito qué versión utilizaste, dónde la descargaste y qué tipo de comillas utilizaste? Por favor. 

Saludos y gracias.

**Comment by melguel** [comment]
Sí claro, la versión que aparece es RTMDump 2.4 git-b627335 2011-7-23, y las comillas que puse son las de la tecla del numero 2, es decir " ", recordar que en sistema operativo windows, respecto a la descarga no conservo el historial lo siento, y muchas gracias!

**Comment by aabilio** [comment]
Gracias ;)

**Comment by frentemorao** [comment]
buenas

Utilizo este post para no abrir otro. 

Antes de navidad no tenía problemas para descargarme videos desde mtv.es en mi raspberry (cogiendo el código de pydowntv y con el rtmp).

Ahora, de vuelta a la rutina, estoy intentando descargarme este mp4 (http://www.mtv.es/programas/geordie-shore-6-temporada/episodios/geordie-shore-608/video/geordie-shore-ep-608-parte-1-de-4-989828/) sin éxito.

En lugar del enlace correcto obtengo lo siguiente:

rtmpdump -r 'rtmp<?xml version="1.0" encoding="UTF-8"?>

<package version="1.4">
<video>
<item>
<rendition duration="10" width="400" height="300" type="application/x-shockwave-flash">

<src>http://intl.esperanto.mtvi.com/www/custom/intl/errorslates/copyright_error.flv?geo%3Dus' -o 'Geordie_Shore_Ep.608_Parte_1_de_4.mp4'

¿ALGUNA IDEA?

**Comment by denobisipsis** [comment]
rtmpdump  -r "rtmpe://cp35019.edgefcs.net/ondemand/mtviestor/_!/intlod/es/tv/GEORDIE-SHORE-6-TEMP/gs608_1280x720_3500_h32.mp4"
-o etwas.mp4

**Comment by frentemorao** [comment]
gracias!!

me ha funcionado cambiando las " por ' y poniendo en la misma linea -o etwas.mp4

**Comment by frentemorao** [comment]
denobis, me ayudas con el 7x01 y 7x02 de Geordie Shore??

http://www.pydowntv.com/?url=http%3A//www.mtv.es/programas/geordie-shore-temporada-7/episodios/geordie-shore-702/video/geordie-shore-ep-702-parte-1-de-4-992421/

http://www.pydowntv.com/?url=http%3A//www.mtv.es/programas/geordie-shore-temporada-7/episodios/geordie-shore-701/video/geordie-shore-ep-701-parte-1-de-4-991405/

**Comment by aabilio** [comment]
rtmpdump -r 'rtmpe://cp35019.edgefcs.net/ondemand/mtviestor/_!/intlod/es/tv/GEORDIE-SHORE-7-TEMP/gs-702_1280x720_3500_h32.mp4' -o 'Geordie_Shore_Ep.702_Parte_1_de_4.mp4'

rtmpdump -r 'rtmpe://cp35019.edgefcs.net/ondemand/mtviestor/_!/intlod/es/tv/GEORDIE-SHORE-7-TEMP/gs-701_1280x720_3500_h32.mp4' -o 'Geordie_Shore_Ep.701_Parte_1_de_4.mp4'

El error de pydowntv se debe a los cambios en un proxy que he hecho hace poco. Espero poder solucionarlo dentro de poco. Saludos.

**Comment by frentemorao** [comment]
muchas gracias!!

para futuras descargas, hay alguna manera de sacar el código sin molestarte??

**Comment by aabilio** [comment]
Si utilizas el script de pydowntv y estás en España no deberías tener
problemas:

./pydowntv -n "http://www.mtv...." para descargar (debes tener instalado
RTMPDUMP para mtv)
./pydowntv -ns "http://www.mtv...." para ver el enlace

aabilio - http://web.pydowntv.com
GPG id 81D115C4 Abilio Almeida Eiroa (aabilio)
SIP: aabilio@ekiga.net Skype: @a_abilio

2014/1/13 frentemorao notifications@github.com

**Comment by aabilio** [comment]
Bueno, si usas Windows, necesitas instalar Python (http://www.python.org/ftp/python/2.7.6/python-2.7.6.msi) y llamar al script desde el:

C:\Python2.7\python.exe pydowntv.py -ns "..." (*)

(*)
La C:\ depende de dónde hayas instalado python y la versión la que hayas instalado..
Tienes que estar en la consola donde esté descargado pydowntv.py.. que lo puedes descargar desde aquí (Github: https://github.com/aabilio/PyDownTV2/archive/master.zip) y está en la carpeta "Script".

**Comment by frentemorao** [comment]
Utilizo la raspberry (por lo tanto debian) y para coger el enlace, el plugin de chrome en windows xp (luego me conecto con putty a la raspberry y lo pongo a descargar)

Estoy en España y durante 2013 me he descargado sin problemas dos temporadas enteras de Geordie Shore.
Ahora me da ese error... (voy a ver si se debe a otro plugin que tengo instalado...)

**Comment by frentemorao** [comment]
Abilio, otra cosa... no me funcionan tus enlaces... me da el siguiente error:
ERROR: Closing connection: NetStream.Play.StreamNotFound

**Comment by aabilio** [comment]
Bueno, pues entonces no necesitas python, por que en Debian viene instalado...

1.- Te conectas a la Rasp con a través de ssh como vienes haciendo
2.- Te bajas en el directorio que quieras Pydowntv:

``` bash
$ cd Downloads (por ejemplo)
$ wget https://github.com/aabilio/PyDownTV2/archive/master.zip
```

3.- Descomprimes el paquete:

``` bash
unzip master.zip
```

4.- Te vas al directorio del script:

``` bash
cd PyDownTV2-master/Script/
```

5.- Ejecutas pydowntv para descargar el capítulo:

``` bash
./pydowntv.py -n "http://www.mtv.es/programas/geordie-shore-temporada-7/episodios/geordie-shore-701/video/geordie-shore-ep-701-parte-1-de-4-991405/"
```

o solo para ver los comandos:

``` bash
./pydowntv.py -ns "http://www.mtv.es/programas/geordie-shore-temporada-7/episodios/geordie-shore-701/video/geordie-shore-ep-701-parte-1-de-4-991405/"
```

**Comment by aabilio** [comment]
@frentemorao sobre el error `ERROR: Closing connection: NetStream.Play.StreamNotFound` es el mismo que le daba a @melguel (mirar más arriba en este mismo hilo) y dijo que se solucionó actualizando rtmpdump...

**Comment by frentemorao** [comment]
yo antes utilizaba directamente rtmdump pero voy a probar tu script!!

En relación a los enlaces, he desinstalado el plugin de chrome "multiaccount login" por si interfería con tu plugin y lamentablemente tengo que decir que sigo obteniendo código erróneo...

**Comment by aabilio** [comment]
@frentemorao ya comenté arriba que la versión online de pydowntv para mtv tiene un error debido a un proxy que he dejado de utilizar, por eso hasta que lo arregle, seguirá fallando (necesita proxy por que los servers de pydowntv están fuera de España).
Te propongo usar la versión offline (local) de pydowntv (que te digo arriba) para alcanzar los enlaces de mtv. Esta versión debería funcionar si el PC/Mac/Rasp/... que lo ejecuta está en España.

PD.: La versión local de PyDownTV sigue necesitando RTMPDUMP para descargar los vídeo que las cadenas disponen a través de RTMP.
PD.: Ningún complemento debería interferir en el correcto funcionamiento de pydowntv a no ser que este esté diseñado específicamente en las webs que abres con el navegador.

**Comment by aabilio** [comment]
@frentemorao más info sobre el error de los enlaces que copie antes.. parece que Github borró algunos caracteres de la URL:

``` bash
rtmpdump -r 'rtmpe://cp35019.edgefcs.net/ondemand/mtviestor/_!/intlod/es/tv/GEORDIE-SHORE-7-TEMP/gs-701_1280x720_3500_h32.mp4' -o 'Geordie_Shore_Ep.701_Parte_1_de_4.mp4'

rtmpdump -r 'rtmpe://cp35019.edgefcs.net/ondemand/mtviestor/_!/intlod/es/tv/GEORDIE-SHORE-7-TEMP/gs-702_1280x720_3500_h32.mp4' -o 'Geordie_Shore_Ep.702_Parte_1_de_4.mp4
```

**Comment by frentemorao** [comment]
acabo de probar la versión offline y de lujo!!
edito para decir que también de lujo con los enlaces que acabas de poner (incluyendo los caracteres que borró Github)

**Comment by frentemorao** [comment]
aunque los videos los descarga perfecto, suelo tener este mensaje al finalizar la descarga...

Download complete
Traceback (most recent call last):
  File "./pydowntv.py", line 247, in <module>
    d.descargarVideo()
  File "/home/pi/PyDownTV2-master/Script/uiDescargar.py", line 140, in descargarVideo
    elif self.__TIPO == "rtmp" or self.__TIPO == "rtmpe": self.__getRTMP()
  File "/home/pi/PyDownTV2-master/Script/uiDescargar.py", line 102, in __getRTMP
    printt(u"[OK] Descarga realizada con Ã©xito")
  File "/home/pi/PyDownTV2-master/Script/uiUtiles.py", line 66, in printt
    print i,
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 28: ordinal not in range(128)

es normal??

**Comment by aabilio** [comment]
Es un pequeño error de codificación que tengo que revisar, pero no debería tener mucha importancia..

**Comment by frentemorao** [comment]
aabilio, estoy intentando descargar desde la raspberry con el offline y me da error de permisos...
